---
- name: Update group4 server
  hosts: centos
  become: yes
  vars:
    httpd_port: 8089
  tasks:
  
  - name: update the webpage
    template:
      src: httpd.j2
      dest: /etc/httpd/conf/httpd.conf
    notify:
    -  restart httpd
    when: ansible_distribution == "CentOS" or ansible_distribution == "Amazon" 
   

  - name: install php
    yum:
      name: php
      state: present
    when: ansible_distribution == "CentOS" or ansible_distribution == "Amazon"

  handlers:
  - name: restart httpd 
    service:
      name: httpd
      state: restarted
    when: ansible_distribution == "CentOS" or ansible_distribution == "Amazon"

...
